# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csz/Code/simple-state

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csz/Code/simple-state

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/local/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csz/Code/simple-state/CMakeFiles /home/csz/Code/simple-state//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csz/Code/simple-state/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stm32_state_demo

# Build rule for target.
stm32_state_demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stm32_state_demo
.PHONY : stm32_state_demo

# fast build rule for target.
stm32_state_demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32_state_demo.dir/build.make CMakeFiles/stm32_state_demo.dir/build
.PHONY : stm32_state_demo/fast

#=============================================================================
# Target rules for targets named state_machine_tests

# Build rule for target.
state_machine_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 state_machine_tests
.PHONY : state_machine_tests

# fast build rule for target.
state_machine_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/state_machine_tests.dir/build.make CMakeFiles/state_machine_tests.dir/build
.PHONY : state_machine_tests/fast

src/demo_main.o: src/demo_main.cpp.o
.PHONY : src/demo_main.o

# target to build an object file
src/demo_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32_state_demo.dir/build.make CMakeFiles/stm32_state_demo.dir/src/demo_main.cpp.o
.PHONY : src/demo_main.cpp.o

src/demo_main.i: src/demo_main.cpp.i
.PHONY : src/demo_main.i

# target to preprocess a source file
src/demo_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32_state_demo.dir/build.make CMakeFiles/stm32_state_demo.dir/src/demo_main.cpp.i
.PHONY : src/demo_main.cpp.i

src/demo_main.s: src/demo_main.cpp.s
.PHONY : src/demo_main.s

# target to generate assembly for a file
src/demo_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32_state_demo.dir/build.make CMakeFiles/stm32_state_demo.dir/src/demo_main.cpp.s
.PHONY : src/demo_main.cpp.s

tests/state_machine_test.o: tests/state_machine_test.cpp.o
.PHONY : tests/state_machine_test.o

# target to build an object file
tests/state_machine_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/state_machine_tests.dir/build.make CMakeFiles/state_machine_tests.dir/tests/state_machine_test.cpp.o
.PHONY : tests/state_machine_test.cpp.o

tests/state_machine_test.i: tests/state_machine_test.cpp.i
.PHONY : tests/state_machine_test.i

# target to preprocess a source file
tests/state_machine_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/state_machine_tests.dir/build.make CMakeFiles/state_machine_tests.dir/tests/state_machine_test.cpp.i
.PHONY : tests/state_machine_test.cpp.i

tests/state_machine_test.s: tests/state_machine_test.cpp.s
.PHONY : tests/state_machine_test.s

# target to generate assembly for a file
tests/state_machine_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/state_machine_tests.dir/build.make CMakeFiles/state_machine_tests.dir/tests/state_machine_test.cpp.s
.PHONY : tests/state_machine_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... state_machine_tests"
	@echo "... stm32_state_demo"
	@echo "... src/demo_main.o"
	@echo "... src/demo_main.i"
	@echo "... src/demo_main.s"
	@echo "... tests/state_machine_test.o"
	@echo "... tests/state_machine_test.i"
	@echo "... tests/state_machine_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

